spring:
  application:
    name: associacao
  datasource:
    url: jdbc:h2:mem:associacao
    username: vila
    password: vila123
  jpa:
    database:platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
