spring:
  application:
    name: associacao
  datasource:
    url: jdbc:postgresql://localhost:5432/associacao
    username: vila
    password: vila123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true